services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped
    networks:
      - algobrain-network
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - algobrain-network
    volumes:
      - ./frontend/src:/app/src
    command: ["npm", "run", "dev"]

networks:
  algobrain-network:
    driver: bridge